"""
Django settings for helloworldproject project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

# 全体の設定ファイル

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 秘密鍵
SECRET_KEY = 'u+m57m&t6s7f2jw2^y(v1h-f^rrqla)luy714ua67oep7y4p1^'

# SECURITY WARNING: don't run with debug turned on in production!
# trueの時には詳しいエラー情報が出てくる、つまり開発環境でTrueにする
DEBUG = True

# 外部のwebサーバーのipアドレスを入れる
# ここに指定したアドレスのみアクセス可能にする
ALLOWED_HOSTS = []


# Application definition
# 機能ごとに作ったアプリをここに追加していく、機能を細切れに分けていき、Djangoに認識させていく
INSTALLED_APPS = [
    'django.contrib.admin', # 管理サイト機能
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# 間に入って何かしてくれる、結構上級編なので基礎編では触れないのかな？
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',# ユーザーのセッション管理ミドルウェア
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ブラウザで受けたURLを最初に受け取るところ、つまりは玄関みたいなもの
ROOT_URLCONF = 'helloworldproject.urls'

# HTMLファイルをどこに入れるのか?といったもの
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # どこにHTMLファイルが入っているのか支持をだす
        # BASE_DIRとは？
        # 
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# wsgiのディレクトリ
WSGI_APPLICATION = 'helloworldproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# データベースの接続情報など、デフォルトではsqliteを使う
# データベースの設定
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
# パスワードのバリデーション、型とかlenなど

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
# 言語やタイムゾーン

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# CSSや画像ファイルなど
# URLで呼び出し方など

STATIC_URL = '/static/'
